spring:
  application:
    name: demo-chat-client
  ai:
    ollama:
      chat:
        model: gemma4
        keep-alive: 30m
      base-url: http://127.0.0.1:11434
#      base-url: http://localhost:8090/ollama
    mcp:
      client:
        streamable-http:
          connections:
            mcp-weather:
#              url: http://localhost:8080
              url: http://localhost:8090
              endpoint: /mcp-weather



#logging:
#  level:
#    root: debug